#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=24:00:00
#SBATCH --partition=matgen_prior
#SBATCH --account=matgen
#SBATCH --job-name=all_launch_dirs
#SBATCH --output=all_launch_dirs-%j.out
#SBATCH --error=all_launch_dirs-%j.error

module unload python
module unload virtualenv
module load python/3.4-anaconda
module unload intel
source activate /global/u1/h/huck/ph_atomate

srun -n 1 python all_launch_dirs.py
